use quick_xml::Reader;
use serde::Deserialize;
use std::collections::HashMap;
use std::ops::RangeInclusive;
use std::path::{Path, PathBuf};
use std::{env, fs};

mod extraction;
mod generation;

const OUT_DIR: &str = "OUT_DIR";
const TARGET_ENV_VAR: &str = "TARGET_GENERATED_SISO_REF_010_FILENAME";
const TARGET_OUT_FILE: &str = "siso_ref_010.rs";

const WRAP_ENUM_UID_OFFSET: usize = 100_000;
const WRAP_ENUM_TRIM_NAME: &str = " Type";
const WRAP_ENUM_SIZE: usize = 32; // NOTE Now a hardcoded size, as both capabilities and (extended) appearance are 32 bits.

// TODO generate the record types as well (31 items), and implement xref's to these records

/// Some enums cross-reference "record" elements.
/// Such records are not generated by this script
/// and must be excluded using the `SKIP_XREF_UIDS` array.
///
/// The `EnumItem::CrossRef` variant that would normally be constructed
/// from the XML structure will be changed to a regular `EnumItem::Basic`
const SKIP_XREF_UIDS: [usize; 1] = [220];

#[derive(Debug, Clone)]
pub enum GenerationItem {
    Enum(Enum),
    Bitfield(Bitfield),
}

impl<'a> GenerationItem {
    #[must_use]
    pub fn uid(&self) -> usize {
        match self {
            GenerationItem::Enum(e) => e.uid,
            GenerationItem::Bitfield(b) => b.uid,
        }
    }

    #[must_use]
    pub fn name(&'a self) -> &'a str {
        match self {
            GenerationItem::Enum(e) => e.name.as_str(),
            GenerationItem::Bitfield(b) => b.name.as_str(),
        }
    }

    #[must_use]
    pub fn size(&self) -> usize {
        match self {
            GenerationItem::Enum(e) => e.size,
            GenerationItem::Bitfield(b) => b.size,
        }
    }
}

#[allow(dead_code)]
#[derive(Debug, Clone)]
pub struct Enum {
    pub uid: usize,
    pub name: String,
    pub size: usize,
    pub items: Vec<EnumItem>,
    pub discriminant: Option<String>,
}

#[derive(Debug, Clone)]
pub enum EnumItem {
    Basic(BasicEnumItem),
    Range(RangeEnumItem),
    CrossRef(CrossRefEnumItem),
}

#[derive(Debug, Clone)]
pub struct BasicEnumItem {
    pub description: String,
    pub value: usize,
    #[allow(
        unused,
        reason = "Deprecated items are included for full compatibility."
    )]
    pub deprecated: bool,
}

#[derive(Debug, Clone)]
pub struct RangeEnumItem {
    pub description: String,
    pub range: RangeInclusive<usize>,
    #[allow(
        unused,
        reason = "Deprecated items are included for full compatibility."
    )]
    pub deprecated: bool,
}

#[derive(Debug, Clone)]
pub struct CrossRefEnumItem {
    pub description: String,
    pub value: usize,
    pub xref: usize,
    #[allow(
        unused,
        reason = "Deprecated items are included for full compatibility."
    )]
    pub deprecated: bool,
}

#[derive(Debug, Clone)]
pub struct Bitfield {
    pub uid: usize,
    pub name: String,
    pub size: usize,
    pub fields: Vec<BitfieldItem>,
}

#[derive(Debug, Clone)]
pub struct BitfieldItem {
    pub name: String,
    pub bit_position: usize,
    pub length: usize,
    pub xref: Option<usize>,
    pub description: String,
}

type Overrides = HashMap<usize, UidOverride>;

/// An `UidOverride` record is used to store overrides for UID items.
/// Available configurations are:
/// - `name`: Change the name of the to-be generated item (e.g. `Some Very Long Name` becomes `ShorterName`);
/// - `size`: Change the data size of the to-be generated item (e.g. '5' becomes '16').
/// - `postfix_value` Postfix fields of enumeration items with their value, because duplicate fields names exist in the SISO-REF-010 definitions.
/// - `skip`: Completely skip the item of being generated.
/// - `xref`: Handling of cross-referenced (`xref`) UID items in the enum variant. By default these xref'ed items are not considered.
///     - the value `"embed"` contains the xref UID in the enum variant.
///     - the value `"wrapper"` generates the enum as default, and also generates a similar enum that does embed the xrefs, for use in enum type and adaptive fields, respectively.
#[derive(Default, Debug)]
struct UidOverride {
    name: Option<String>,
    size: Option<usize>, // TODO see if we can derive this override when extracting or generating.
    postfix_value: bool,
    skip: bool,
    xref: OverrideXrefHandling,
}

impl From<OverrideEntry> for UidOverride {
    fn from(entry: OverrideEntry) -> Self {
        Self {
            name: entry.name,
            size: entry.size,
            postfix_value: entry.postfix.unwrap_or(false),
            skip: entry.skip.unwrap_or(false),
            xref: OverrideXrefHandling::from(&entry.xref),
        }
    }
}

#[derive(Default, Debug, PartialEq)]
enum OverrideXrefHandling {
    #[default]
    None,
    Embed,
    Wrap,
}

impl From<&Option<String>> for OverrideXrefHandling {
    fn from(value: &Option<String>) -> Self {
        const EMBED_CONFIG_STR: &str = "embed";
        const WRAPPER_CONFIG_STR: &str = "wrapper";
        match value {
            Some(s) if s == EMBED_CONFIG_STR => OverrideXrefHandling::Embed,
            Some(s) if s == WRAPPER_CONFIG_STR => OverrideXrefHandling::Wrap,
            _ => OverrideXrefHandling::None,
        }
    }
}

#[derive(Debug, Deserialize)]
struct OverrideConfig {
    overrides: HashMap<usize, OverrideEntry>,
}

#[derive(Debug, Deserialize)]
struct OverrideEntry {
    name: Option<String>,
    size: Option<usize>,
    postfix: Option<bool>,
    skip: Option<bool>,
    xref: Option<String>,
}

fn init_overrides(path: &Path) -> Overrides {
    let config_str = fs::read_to_string(path).expect("Failed to read overrides file");
    let config: OverrideConfig =
        toml::from_str(&config_str).expect("Failed to parse overrides file");

    let mut overrides = Overrides::new();

    for entry in config.overrides {
        overrides.insert(entry.0, UidOverride::from(entry.1));
    }

    overrides
}

/// This is the main entry point for generating the enumerations
/// as defined in the SISO-REF-010 reference document.
///
/// The `siso_ref_010_file` argument is a `&str` to the XML defining the enumerations.
///
/// # Panics
/// When errors are encountered when parsing the XML the function panics.
/// As this function is to be called from within a build script,
/// aborting by panicking is acceptable.
#[must_use]
pub fn execute(
    siso_ref_010_dir: &str,
) -> (
    HashMap<usize, String>,
    HashMap<usize, String>,
    HashMap<usize, String>,
) {
    let ref_path: PathBuf = [siso_ref_010_dir, "SISO-REF-010.xml"].iter().collect();
    let config_path: PathBuf = [siso_ref_010_dir, "overrides.toml"].iter().collect();
    let overrides = init_overrides(config_path.as_path());

    let mut reader = Reader::from_file(ref_path.as_path()).unwrap();
    reader.config_mut().trim_text(true);

    // Extract enums and bitfields from the source file
    let generation_items = extraction::extract(&mut reader);

    let wrapper_items = generation_items
        .iter()
        .filter_map(|item| {
            if let GenerationItem::Enum(e) = item {
                if overrides
                    .get(&e.uid)
                    .is_some_and(|entry| entry.xref == OverrideXrefHandling::Wrap)
                {
                    let wrapper_item = Enum {
                        uid: e.uid + WRAP_ENUM_UID_OFFSET,
                        name: e.name.trim_end_matches(WRAP_ENUM_TRIM_NAME).to_string(),
                        size: WRAP_ENUM_SIZE,
                        items: e.items.clone(),
                        discriminant: Some(e.name.clone()),
                    };
                    Some(wrapper_item)
                } else {
                    None
                }
            } else {
                None
            }
        })
        .collect::<Vec<Enum>>();

    let mut overrides = overrides;
    let mut generation_items = generation_items;
    for it in wrapper_items {
        overrides.insert(
            it.uid,
            UidOverride {
                xref: OverrideXrefHandling::Embed,
                ..Default::default()
            },
        );
        generation_items.push(GenerationItem::Enum(it));
    }
    let overrides = overrides;
    let generation_items = generation_items;

    // Build the index of UIDs and their code names
    let uid_index = create_uid_index(&generation_items);
    let pdu_index = create_pdu_types_index(&generation_items);
    let er_index = create_extension_record_types_index(&generation_items);

    // Generate the code for the enumerations
    generate_and_save(&generation_items, &overrides);

    (uid_index, pdu_index, er_index)
}

/// Create an index of UIDs to the name of the generated code items
/// for use in further generation functions.
fn create_uid_index(generation_items: &[GenerationItem]) -> HashMap<usize, String> {
    let mut uid_index = HashMap::new();

    for item in generation_items {
        uid_index.insert(item.uid(), format_name(item.name(), item.uid()));
    }

    // FIXME remove these placeholders when the v8 standard is complete
    uid_index.insert(93, "EnumerationU32".to_string()); // FIXME not defined in SISO-REF-010 v36 - Mode S Squitter Reports p436 l17 - u32
    uid_index.insert(94, "EnumerationU8".to_string()); // FIXME not defined in SISO-REF-010 v36 - TCAS/ACAS system Type - p440 l22 - u8
    uid_index.insert(95, "EnumerationU8".to_string()); // FIXME not defined in SISO-REF-010 v36 - Mode 4 Status - Active Cde Key - p418 l20 - u8
    uid_index.insert(490, "EnumerationU8".to_string()); // FIXME not defined in SISO-REF-010 v36 - not in draft 5 doc - SIMAN Radar Track Status - u8
    uid_index.insert(544, "EnumerationU8".to_string()); // FIXME not defined in SISO-REF-010 v36 - not in draft 5 doc - EII Thermal Part Part - u8
    uid_index.insert(554, "EnumerationU8".to_string()); // FIXME not defined in SISO-REF-010 v36 - Current/Requested Application Mode - p341 l12 - u8
    uid_index.insert(567, "EnumerationU8".to_string()); // FIXME not defined in SISO-REF-010 v36 - Current/Requested Application/exercise State - p339 - u8
    uid_index.insert(569, "EnumerationU8".to_string()); // FIXME not defined in SISO-REF-010 v36 - Application General Status - p189/354/357 - u8
    uid_index.insert(570, "EnumerationU8".to_string()); // FIXME not defined in SISO-REF-010 v36 - Application Specific Status - p189/354/357 - u8
    uid_index.insert(571, "EnumerationU8".to_string()); // FIXME not defined in SISO-REF-010 v36 - Application Transition - p351/353 - u8
    uid_index.insert(572, "EnumerationU8".to_string()); // FIXME not defined in SISO-REF-010 v36 - Exercise Transition - p351 - u8
    uid_index.insert(573, "EnumerationU16".to_string()); // FIXME not defined in SISO-REF-010 v36 - Status Type - p354/356/357/360 - u16
    uid_index.insert(579, "EnumerationU8".to_string()); // FIXME not defined in SISO-REF-010 v36 - not in draft 5 doc - SIMAN General Status - u8
    uid_index.insert(657, "EnumerationU8".to_string()); // FIXME not defined in SISO-REF-010 v36 - not in draft 5 doc - Synth Env Cloud Type - u8
    uid_index.insert(665, "EnumerationU8".to_string()); // FIXME not defined in SISO-REF-010 v36 - Layer type - p509 l31 - u8
    uid_index.insert(702, "EnumerationU8".to_string()); // FIXME not defined in SISO-REF-010 v36 - Collision Origin - p78 l16 - u8
    uid_index.insert(790, "EnumerationU8".to_string()); // FIXME not defined in SISO-REF-010 v36 - not in draft 5 doc - EE Shape - u8
    uid_index.insert(791, "EnumerationU8".to_string()); // FIXME not defined in SISO-REF-010 v36 - not in draft 5 doc - EE Lobe Type - u8
    uid_index.insert(880, "EnumerationU8".to_string()); // FIXME not defined in SISO-REF-010 v36 - Motion Pattern - p454 l30 - u8
    uid_index.insert(881, "EnumerationU8".to_string()); // FIXME not defined in SISO-REF-010 v36 - (Laser) Beam Shape - p454 l6 - u8
    uid_index.insert(882, "EnumerationU8".to_string()); // FIXME not defined in SISO-REF-010 v36 - (Laser) Spot Type - p454 l28 - u8
    uid_index.insert(883, "EnumerationU8".to_string()); // FIXME not defined in SISO-REF-010 v36 - (Laser) Beam Function - p454 l3 - u8
    uid_index.insert(884, "EnumerationU8".to_string()); // FIXME not defined in SISO-REF-010 v36 - (Laser) Flash Pattern - p454 l8 - u8

    uid_index
}

fn create_pdu_types_index(generation_items: &[GenerationItem]) -> HashMap<usize, String> {
    let pdu_type_enum = generation_items.iter().find(|&item| {
        if let GenerationItem::Enum(e) = item {
            e.uid == 4
        } else {
            false
        }
    });

    let mut pdu_types_index = HashMap::new();

    if let Some(GenerationItem::Enum(e)) = pdu_type_enum {
        for item in &e.items {
            if let EnumItem::Basic(variant) = item {
                pdu_types_index.insert(variant.value, format_name(&variant.description, 0));
            }
        }
    }

    pdu_types_index
}

fn create_extension_record_types_index(
    generation_items: &[GenerationItem],
) -> HashMap<usize, String> {
    let er_type_enum = generation_items.iter().find(|&item| {
        if let GenerationItem::Enum(e) = item {
            e.uid == 99
        } else {
            false
        }
    });

    let mut er_types_index = HashMap::new();

    if let Some(GenerationItem::Enum(e)) = er_type_enum {
        for item in &e.items {
            if let EnumItem::Basic(variant) = item {
                er_types_index.insert(variant.value, format_name(&variant.description, 0));
            }
        }
    }

    // FIXME remove these placeholders when the v8 standard is complete - added by hand to SISO-REF-010.xml file
    // er_types_index.insert(2042, format_name("AnimationControl", 0)); // v36 UID 99 does not contain this type variant
    // er_types_index.insert(3102, format_name("MultipleNodes", 0)); // v36 UID 99 does not contain this type variant
    // er_types_index.insert(5503, format_name("IOComputedEffects", 0)); // v36 UID 99 does not contain this type variant

    er_types_index
}

/// Generates code for all provided `GenerationItem`s, formats the code and stores it in `OUT_DIR`.
fn generate_and_save(generation_items: &[GenerationItem], overrides: &Overrides) {
    // Generate all code for enums
    let generated = generation::generate(generation_items, overrides);

    // format generated code using prettyplease
    let ast = syn::parse_file(&generated.to_string())
        .expect("Error parsing generated code for pretty printing.");
    let contents = prettyplease::unparse(&ast);

    // Save to file
    let dest_path = Path::new(&env::var(OUT_DIR).unwrap()).join(TARGET_OUT_FILE);
    fs::write(dest_path, contents).unwrap();

    // Set file name to an environment variable, for inclusion in the to-be compiled library
    println!("cargo:rustc-env={TARGET_ENV_VAR}={TARGET_OUT_FILE}");
}

fn format_name_postfix(value: &str, uid: usize, needs_postfix: bool) -> String {
    #[allow(clippy::collapsible_str_replace)]
    let intermediate: String = value
        // Remove / replace the following characters
        .replace('-', "")
        .replace('/', "")
        .replace('.', "_")
        .replace(',', "_")
        .replace('\'', "")
        .replace('#', "")
        .replace("&quot;", "")
        .replace("&amp;", "")
        .replace(';', "")
        .replace(':', "")
        .replace('(', "_")
        .replace(')', "_")
        .replace('{', "_")
        .replace('}', "_")
        .replace('=', "_")
        .replace('–', "_")
        .replace('+', "plus")
        .replace('%', "pct")
        // Split by white space (1), capitalize each substring (2), then merge (3).
        // Example procedure for "Life form":
        // 1 | Split      : ["Life", "form"]
        // 2 | Capitalize : ["Life", "Form"]
        // 3 | Merge      : "LifeForm"
        .split(' ')
        .map(|string| {
            let mut chars = string.chars();
            match chars.next() {
                // Empty string
                None => String::new(),
                // Uppercase character and concatenate
                Some(char) => format!("{}{}", char.to_uppercase(), chars.as_str()),
            }
        })
        .map(|string| string.trim_end_matches('_').to_string()) // trim trailing underscores
        .collect();

    // Prefix values starting with a digit with '_'
    // FIXME .unwrap_or('x') is a hack to fail when `intermediate` is empty. is_some_and() is unstable at this time.
    let starts_with_digit = intermediate.chars().next().unwrap_or('x').is_ascii_digit();
    let is_empty = intermediate.is_empty();

    let prefix = String::from(if starts_with_digit { "_" } else { "" });
    let name = if is_empty {
        String::from("Unnamed")
    } else {
        intermediate
    };
    let postfix = if needs_postfix {
        format!("_{uid}")
    } else {
        String::new()
    };
    let intermediate = [prefix, name, postfix].join("");

    // When there are multiple parenthesis sections, replace them with '_' (such as Countries)
    intermediate.replace("__", "_")
}

fn format_name(value: &str, uid: usize) -> String {
    format_name_postfix(value, uid, false)
}

fn format_field_name(name: &str) -> String {
    #[allow(clippy::collapsible_str_replace)]
    name.to_lowercase()
        .replace(" / ", "_")
        .replace(' ', "_")
        .replace('-', "")
        .replace('/', "_")
        .replace('#', "")
        .replace('(', "")
        .replace(')', "")
        .replace('=', "_")
        .replace('\'', "")
}

fn escape_description(description: &str) -> String {
    description.replace('{', "{{").replace('}', "}}")
}

#[cfg(test)]
mod tests {
    // #[test]
    // fn test_format_name() {}
}
