use crate::dis::common::model::ProtocolVersion;
use crate::dis::v6::other::model::Other;
use super::entity_state::model::EntityState;

// TODO re-export the PDU types
// TODO review pub settings in PDU modules

pub const PDU_HEADER_LEN_BYTES : usize = 96;

pub struct PduHeader {
    pub protocol_version : ProtocolVersion,
    pub exercise_id : u8,
    pub pdu_type : PduType,
    pub protocol_family : ProtocolFamily,
    pub time_stamp : u32,
    pub pdu_length : u16,
    pub padding : u16,
}

pub enum PduType {
    OtherPdu = 0,
    EntityStatePdu = 1,
    FirePdu = 2,
    DetonationPdu = 3,
    CollisionPdu = 4,
    ServiceRequestPdu = 5,
    ResupplyOfferPdu = 6,
    ResupplyReceivedPdu = 7,
    ResupplyCancelPdu = 8,
    RepairCompletePdu = 9,
    RepairResponsePdu = 10,
    CreateEntityPdu = 11,
    RemoveEntityPdu = 12,
    StartResumePdu = 13,
    StopFreezePdu = 14,
    AcknowledgePdu = 15,
    ActionRequestPdu = 16,
    ActionResponsePdu = 17,
    DataQueryPdu = 18,
    SetDataPdu = 19,
    DataPdu = 20,
    EventReportPdu = 21,
    CommentPdu = 22,
    ElectromagneticEmissionPdu = 23,
    DesignatorPdu = 24,
    TransmitterPdu = 25,
    SignalPdu = 26,
    ReceiverPdu = 27,
    AnnounceObjectPdu = 129,
    DeleteObjectPdu = 130,
    DescribeApplicationPdu = 131,
    DescribeEventPdu = 132,
    DescribeObjectPdu = 133,
    RequestEventPdu = 134,
    RequestObjectPdu = 135,
    TimeSpacePositionIndicatorFIPdu = 140,
    AppearanceFIPdu = 141,
    ArticulatedPartsFIPdu = 142,
    FireFIPdu = 143,
    DetonationFIPdu = 144,
    PointObjectStatePdu = 150,
    LinearObjectStatePdu = 151,
    ArealObjectStatePdu = 152,
    EnvironmentPdu = 153,
    TransferControlRequestPdu = 155,
    TransferControlPdu = 156,
    TransferControlAcknowledgePdu = 157,
    IntercomControlPdu = 160,
    IntercomSignalPdu = 161,
    AggregatePdu = 170,
}

impl From<u8> for PduType {
    fn from(value: u8) -> Self {
        match value {
            1 => PduType::EntityStatePdu,
            2 => PduType::FirePdu,
            3 => PduType::DetonationPdu,
            4 => PduType::CollisionPdu,
            5 => PduType::ServiceRequestPdu,
            6 => PduType::ResupplyOfferPdu,
            7 => PduType::ResupplyReceivedPdu,
            8 => PduType::ResupplyCancelPdu,
            9 => PduType::RepairCompletePdu,
            10 => PduType::RepairResponsePdu,
            11 => PduType::CreateEntityPdu,
            12 => PduType::RemoveEntityPdu,
            13 => PduType::StartResumePdu,
            14 => PduType::StopFreezePdu,
            15 => PduType::AcknowledgePdu,
            16 => PduType::ActionRequestPdu,
            17 => PduType::ActionResponsePdu,
            18 => PduType::DataQueryPdu,
            19 => PduType::SetDataPdu,
            20 => PduType::DataPdu,
            21 => PduType::EventReportPdu,
            22 => PduType::CommentPdu,
            23 => PduType::ElectromagneticEmissionPdu,
            24 => PduType::DesignatorPdu,
            25 => PduType::TransmitterPdu,
            26 => PduType::SignalPdu,
            27 => PduType::ReceiverPdu,
            129 => PduType::AnnounceObjectPdu,
            130 => PduType::DeleteObjectPdu,
            131 => PduType::DescribeApplicationPdu,
            132 => PduType::DescribeEventPdu,
            133 => PduType::DescribeObjectPdu,
            134 => PduType::RequestEventPdu,
            135 => PduType::RequestObjectPdu,
            140 => PduType::TimeSpacePositionIndicatorFIPdu,
            141 => PduType::AppearanceFIPdu,
            142 => PduType::ArticulatedPartsFIPdu,
            143 => PduType::FireFIPdu,
            144 => PduType::DetonationFIPdu,
            150 => PduType::PointObjectStatePdu,
            151 => PduType::LinearObjectStatePdu,
            152 => PduType::ArealObjectStatePdu,
            153 => PduType::EnvironmentPdu,
            155 => PduType::TransferControlRequestPdu,
            156 => PduType::TransferControlPdu,
            157 => PduType::TransferControlAcknowledgePdu,
            160 => PduType::IntercomControlPdu,
            161 => PduType::IntercomSignalPdu,
            170 => PduType::AggregatePdu,
            0 | _ => PduType::OtherPdu,
            // unspecified_enum => PduType::Unspecified(unspecified_enum),
        }
    }
}

pub enum ProtocolFamily {
    Other = 0,
    EntityInformationInteraction = 1,
    ExperimentalCGF = 129,
    ExperimentalEntityInteractionInformationFieldInstrumentation = 130,
    ExperimentalWarfareFieldInstrumentation = 131,
    ExperimentalEnvironmentObjectInformationInteraction = 132,
    ExperimentalEntityManagement = 133,
    Warfare = 2,
    Logistics = 3,
    RadioCommunication = 4,
    SimulationManagement = 5,
    DistributedEmissionRegeneration = 6,
    // Unspecified(u8),
}

impl From<u8> for ProtocolFamily {
    fn from(value: u8) -> Self {
        match value {
            1 => ProtocolFamily::EntityInformationInteraction,
            2 => ProtocolFamily::Warfare,
            3 => ProtocolFamily::Logistics,
            4 => ProtocolFamily::RadioCommunication,
            5 => ProtocolFamily::SimulationManagement,
            6 => ProtocolFamily::DistributedEmissionRegeneration,
            129 => ProtocolFamily::ExperimentalCGF,
            130 => ProtocolFamily::ExperimentalEntityInteractionInformationFieldInstrumentation,
            131 => ProtocolFamily::ExperimentalWarfareFieldInstrumentation,
            132 => ProtocolFamily::ExperimentalEnvironmentObjectInformationInteraction,
            133 => ProtocolFamily::ExperimentalEntityManagement,
            0 | _ => ProtocolFamily::Other,
            // unspecified_enum => ProtocolFamily::Unspecified(unspecified_enum),
        }
    }
}

pub enum Pdu {
    Other(Other),
    EntityState(EntityState),
    // TODO implement other PDU structs
    Fire,
    Detonation,
    Collision,
    ServiceRequest,
    ResupplyOffer,
    ResupplyReceived,
    ResupplyCancel,
    RepairComplete,
    RepairResponse,
    CreateEntity,
    RemoveEntity,
    StartResume,
    StopFreeze,
    Acknowledge,
    ActionRequest,
    ActionResponse,
    DataQuery,
    SetData,
    Data,
    EventReport,
    Comment,
    ElectromagneticEmission,
    Designator,
    Transmitter,
    Signal,
    Receiver,
    AnnounceObject,
    DeleteObject,
    DescribeApplication,
    DescribeEvent,
    DescribeObject,
    RequestEvent,
    RequestObject,
    TimeSpacePositionIndicatorFI,
    AppearanceFI,
    ArticulatedPartsFI,
    FireFI,
    DetonationFI,
    PointObjectState,
    LinearObjectState,
    ArealObjectState,
    Environment,
    TransferControlRequest,
    TransferControl,
    TransferControlAcknowledge,
    IntercomControl,
    IntercomSignal,
    Aggregate,
}