name: release

on:
    workflow_run:
        workflows:
            - check
        types:
            - completed

concurrency:
    group: ${{ github.workflow }}
    cancel-in-progress: true

env:
    RUSTFLAGS: -D warnings

jobs:
    release:
        name: Release
        runs-on: ubuntu-latest
        if: github.event.workflow_run.conclusion == 'success' && github.ref_name == 'master' && startsWith(github.event.workflow_run.head_branch, 'v')
        permissions:
            contents: write
            id-token: write
        steps:
            -   name: Checkout
                uses: actions/checkout@v5
                with:
                    ref: ${{ github.event.workflow_run.head_branch }}

            -   name: Setup Rust
                uses: dtolnay/rust-toolchain@master
                with:
                    toolchain: stable

            # TODO changelog & GitHub release

            -   name: Publish
                run: cargo publish --token ${{ secrets.CARGO_REGISTRY_TOKEN }} --verbose --package dis-rs
